---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: elmerbulthuis-cnpe
spec:
  interval: 2m
  url: oci://ghcr.io/elmerbulthuis/cnpe-environment-local-manifest
  ref:
    tag: 0bb36a010d059ef04c7c0faf19fb41e4739102ca

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: environment
spec:
  interval: 2m
  sourceRef:
    kind: OCIRepository
    name: elmerbulthuis-cnpe
  path: manifest.yaml
  prune: false
  timeout: 1m
