---
apiVersion: v1
kind: Pod
metadata:
  name: test-image
spec:
  containers:
    - image: docker.io/library/httpd:2.4
      name: httpd
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi
      restartPolicy: Never
