---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db1
spec:
  instances: 2
  storage:
    storageClass: local
    size: 2Gi
  postgresql:
    pg_hba:
      - host all all 0.0.0.0/0 trust
