---
apiVersion: policy.linkerd.io/v1beta3
kind: Server
metadata:
  name: hello
spec:
  podSelector:
    matchLabels:
      app: hello
  port: 8080
  proxyProtocol: "HTTP/1"
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: allow-authenticated
spec:
  server:
    name: hello
  client:
    meshTLS:
      serviceAccounts:
        - namespace: hello-client
          name: default
