---
apiVersion: v1
kind: Pod
metadata:
  name: test-verify-image-keyless
spec:
  containers:
    - image: ghcr.io/elmerbulthuis/cnpe-hello@sha256:a2895ded43ac4999b8ae57daf9d963c53a02bb2f9cb00a94f94d75180d30afe1
      name: container1
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
        limits:
          cpu: 10m
          memory: 10Mi
      restartPolicy: Never
