---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
rules:
  - apiGroups:
      - "argoproj.io"
    resources:
      - "workflowtaskresults"
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-binding
subjects:
  - kind: ServiceAccount
    name: workflow
roleRef:
  kind: Role
  name: workflow-role
  apiGroup: rbac.authorization.k8s.io
