---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/log"
      - "pods/exec"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "delete"

  - apiGroups:
      - "argoproj.io"
    resources:
      - "workflows"
      - "workflowtaskresults"

    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"

  - apiGroups:
      - "events.k8s.io"
    resources:
      - "events"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "patch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-binding
subjects:
  - kind: ServiceAccount
    name: workflow
roleRef:
  kind: Role
  name: workflow-role
  apiGroup: rbac.authorization.k8s.io
